import {
  ANNOUNCEMENT,
  NAV,
  HERO,
  TRUST,
  FEATURES,
  DEPLOY_RAIL,
  WHY,
  CTA_BAND,
  SITE_DESCRIPTION,
  STORY,
  MARQUEE,
  INSTALL,
} from './data';
import { WIKI_GUIDES, WIKI_URL, REPO_URL, GHCR_IMAGE, type RepoMeta } from './github';

const SITE = 'https://zettacrm.com';

/** Homepage content as llms.txt — version/tags pulled live from the repo. */
export function generateLlmsTxt(meta: RepoMeta): string {
  const { latest, tags } = meta;
  const ctaTitle = `${CTA_BAND.titleA} ${CTA_BAND.titleB}`;

  const lines: string[] = [
    `# ${NAV.brand}`,
    '',
    `> ${SITE_DESCRIPTION}`,
    '',
    `Open-source MCP CRM backend for AI agents.`,
    '',
    '## Announcement',
    '',
    `${ANNOUNCEMENT.text} ${ANNOUNCEMENT.suffix}`,
    `- [${ANNOUNCEMENT.cta}](${latest.url})`,
    '',
    '## Hero',
    '',
    HERO.eyebrow,
    '',
    `### ${HERO.brand}${HERO.brandAccent}`,
    '',
    HERO.title,
    '',
    HERO.sub,
    '',
    `- [${HERO.primary.label}](${SITE}${HERO.primary.href})`,
    `- [${HERO.secondary.label}](${HERO.secondary.href})`,
    '',
    '### At a glance',
    '',
    ...TRUST.map((t) => `- **${t.title}**: ${t.desc}`),
    '',
    '## Capability marquee',
    '',
    MARQUEE.join(', '),
    '',
    `## ${STORY.eyebrow}`,
    '',
    `${STORY.left} ${STORY.right}`,
    '',
    ...STORY.steps.map((s, i) => `${i + 1}. **${s.title}**: ${s.desc}`),
    '',
    '## Capabilities',
    '',
    ...FEATURES.flatMap((f) => [
      `### ${f.title}`,
      '',
      f.desc,
      '',
      ...f.points.map((p) => `- ${p}`),
      '',
    ]),
    '## Deploy',
    '',
    `Latest image: \`${GHCR_IMAGE}:${latest.tag}\``,
    '',
    'Set MCP_API_KEY, DB_DSN, and BASE_URL. Authenticate with Bearer or X-API-Key.',
    '',
    `- [Install guide](${SITE}/install)`,
    `- [Release notes](${latest.url})`,
    '',
    ...DEPLOY_RAIL.map((r) => `- **${r.title}**: ${r.sub}`),
    '',
    '## Releases',
    '',
    `Latest: [${latest.tag}](${latest.url})`,
    '',
    ...tags.map((t) => `- [${t.name}](${t.url})`),
    '',
    '## Install guides',
    '',
    `- [On-site install (SEO/GEO)](${SITE}/install)`,
    `- [Install for LLMs](${SITE}/llms-install.txt)`,
    ...WIKI_GUIDES.map((g) => `- [${g.label}](${g.href})`),
    `- [Full wiki](${WIKI_URL})`,
    '',
    '## Why self-hosted',
    '',
    ...WHY.map((w) => {
      const desc = w.highlight ? `${w.highlight} ${w.desc.replace(w.highlight, '').trim()}` : w.desc;
      return `- **${w.title}**: ${desc}`;
    }),
    '',
    '## Get started',
    '',
    `### ${ctaTitle}`,
    '',
    CTA_BAND.sub,
    '',
    `- [${CTA_BAND.primary.label}](${SITE}${CTA_BAND.primary.href})`,
    `- [${CTA_BAND.secondary.label}](${CTA_BAND.secondary.href})`,
    '',
    '## Navigation',
    '',
    ...NAV.links.map((l) => {
      const href = l.href.startsWith('http') ? l.href : `${SITE}${l.href.startsWith('/') ? l.href : `/${l.href}`}`;
      return `- [${l.label}](${href})`;
    }),
    `- [${NAV.github.label}](${NAV.github.href}): ${NAV.github.count}`,
    '',
    '## Pages',
    '',
    `- [${NAV.brand}](${SITE}/): ${SITE_DESCRIPTION}`,
    `- [Install](${SITE}/install): ${INSTALL.description}`,
    `- [llms.txt](${SITE}/llms.txt)`,
    `- [llms-install.txt](${SITE}/llms-install.txt)`,
  ];

  return `${lines.join('\n')}\n`;
}

/** Dedicated install page summary for GEO / LLM crawlers. */
export function generateInstallLlmsTxt(meta: RepoMeta): string {
  const { latest, tags } = meta;

  const lines: string[] = [
    `# Install ${NAV.brand}`,
    '',
    `> ${INSTALL.description}`,
    '',
    `Canonical page: ${SITE}/install`,
    `Source repo: ${REPO_URL}`,
    `Wiki: ${WIKI_URL}`,
    '',
    '## Latest version',
    '',
    `- Tag: [${latest.tag}](${latest.url})`,
    `- Image: \`${GHCR_IMAGE}:${latest.tag}\``,
    `- Pre-release channel: \`${GHCR_IMAGE}:master\``,
    '',
    '## Recent tags',
    '',
    ...tags.map((t) => `- [${t.name}](${t.url}) → \`${GHCR_IMAGE}:${t.name}\``),
    '',
    '## Prerequisites',
    '',
    ...INSTALL.prerequisites.map((p) => `- **${p.title}**: ${p.desc}`),
    '',
    '## Required environment',
    '',
    ...INSTALL.envRequired.map(
      (e) => `- \`${e.name}\` (${e.required ? 'required' : 'optional'}): ${e.notes}`,
    ),
    '',
    '## Docker quickstart',
    '',
    '```bash',
    'docker network create zetta || true',
    '',
    'docker run -d --name zetta-mysql --network zetta \\',
    '  -e MYSQL_ROOT_PASSWORD=rootpass \\',
    '  -e MYSQL_DATABASE=crmagents \\',
    '  -e MYSQL_USER=crmagents \\',
    '  -e MYSQL_PASSWORD=crmagentspass \\',
    '  -v zetta-mysql:/var/lib/mysql \\',
    '  mysql:8',
    '',
    'docker run -d --name zetta-crm --network zetta \\',
    '  -p 8080:8080 \\',
    `  -e MCP_API_KEY='change-me-long-random' \\`,
    `  -e BASE_URL='http://localhost:8080' \\`,
    `  -e DB_DSN='crmagents:crmagentspass@tcp(zetta-mysql:3306)/crmagents?parseTime=true&multiStatements=true' \\`,
    '  -v zetta-exports:/data/exports \\',
    `  ${GHCR_IMAGE}:${latest.tag}`,
    '```',
    '',
    '## Verify',
    '',
    '```bash',
    'curl -fsS http://localhost:8080/healthz',
    '```',
    '',
    'MCP:',
    '',
    '```',
    'MCP_URL=http://localhost:8080/mcp',
    'Authorization: Bearer change-me-long-random',
    '```',
    '',
    '## Public vs private routes',
    '',
    ...INSTALL.routes.map((r) => `- \`${r.path}\` (${r.auth}): ${r.purpose}`),
    '',
    '## Platforms',
    '',
    ...INSTALL.platforms.map((p) => `- [${p.label}](${p.href})`),
    '',
    '## FAQ',
    '',
    ...INSTALL.faq.flatMap((f) => [
      `### ${f.q}`,
      '',
      f.a.replace(/v0\.7\.1/g, latest.tag),
      '',
    ]),
    '## Related',
    '',
    `- [Product home](${SITE}/)`,
    `- [Site summary](${SITE}/llms.txt)`,
    `- [GitHub releases](${REPO_URL}/releases)`,
  ];

  return `${lines.join('\n')}\n`;
}
